---
- name: Configuring Google Cloud HA VPN
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  - name: Setup Global VPC Environment
    tags: ['config-global-vpc']
    command: "{{ item }}"
    with_items:
      - "gcloud compute networks create vpc-demo --subnet-mode custom"
      - "gcloud beta compute networks subnets create vpc-demo-subnet1 --network vpc-demo --range 10.1.1.0/24 --region us-central1"
      - "gcloud beta compute networks subnets create vpc-demo-subnet2 --network vpc-demo --range 10.2.1.0/24 --region us-east1"
      - "gcloud compute firewall-rules create vpc-demo-allow-internal --network vpc-demo --allow tcp:0-65535,udp:0-65535,icmp --source-ranges 10.0.0.0/8"
      - "gcloud compute firewall-rules create vpc-demo-allow-ssh-icmp --network vpc-demo --allow tcp:22,icmp"
      - "gcloud compute instances create vpc-demo-instance1 --zone us-central1-b --subnet vpc-demo-subnet1"
      - "gcloud compute instances create vpc-demo-instance2 --zone us-east1-b --subnet vpc-demo-subnet2"

  - name: Set up a simulated on-premises environment
    tags: ['config-on-prem-vpc']
    command: "{{ item }}"
    with_items:
    - "gcloud compute networks create on-prem --subnet-mode custom"
    - "gcloud beta compute networks subnets create on-prem-subnet1 --network on-prem --range 192.168.1.0/24 --region us-central1"
    - "gcloud compute firewall-rules create on-prem-allow-internal --network on-prem --allow tcp:0-65535,udp:0-65535,icmp --source-ranges 192.168.0.0/16"
    - "gcloud compute firewall-rules create on-prem-allow-ssh-icmp --network on-prem --allow tcp:22,icmp"
    - "gcloud compute instances create on-prem-instance1 --zone us-central1-a --subnet on-prem-subnet1"

  - name: Set up an HA VPN gateway
    tags: ['config-ha-vpn-gateway']
    command: "{{ item }}"
    with_items:
    - "gcloud beta compute vpn-gateways create vpc-demo-vpn-gw1 --network vpc-demo --region us-central1"
    - "gcloud beta compute vpn-gateways create on-prem-vpn-gw1 --network on-prem --region us-central1"
    - "gcloud beta compute vpn-gateways describe vpc-demo-vpn-gw1 --region us-central1"
    - "gcloud beta compute vpn-gateways describe on-prem-vpn-gw1 --region us-central1"

  - name: Create cloud routers
    tags: ['create-cloud-routers']
    command: "{{ item }}"
    with_items:
    - "gcloud compute routers create vpc-demo-router1 --region us-central1 --network vpc-demo --asn 65001"
    - "gcloud compute routers create on-prem-router1 --region us-central1 --network on-prem --asn 65002"

  - name: Create two VPN tunnels
    tags: ['create-vpn-tunnels']
    command: "{{ item }}"
    with_items:
    - "gcloud beta compute vpn-tunnels create vpc-demo-tunnel0 --peer-gcp-gateway on-prem-vpn-gw1 --region us-central1 --ike-version 2 --shared-secret shared_secret --router vpc-demo-router1 --vpn-gateway vpc-demo-vpn-gw1 --interface 0"
    - "gcloud beta compute vpn-tunnels create vpc-demo-tunnel1 --peer-gcp-gateway on-prem-vpn-gw1 --region us-central1 --ike-version 2 --shared-secret shared_secret --router vpc-demo-router1 --vpn-gateway vpc-demo-vpn-gw1 --interface 1"
    - "gcloud beta compute vpn-tunnels create on-prem-tunnel0 --peer-gcp-gateway vpc-demo-vpn-gw1 --region us-central1 --ike-version 2 --shared-secret shared_secret --router on-prem-router1 --vpn-gateway on-prem-vpn-gw1 --interface 0"
    - "gcloud beta compute vpn-tunnels create on-prem-tunnel1 --peer-gcp-gateway vpc-demo-vpn-gw1 --region us-central1 --ike-version 2 --shared-secret shared_secret --router on-prem-router1 --vpn-gateway on-prem-vpn-gw1 --interface 1"

  - name: Create Border Gatway Protocol (BGP) peer for each tunnel
    tags: ["create-bgp-peer"]
    command: "{{ item }}"
    with_items:
    - "gcloud compute routers add-interface vpc-demo-router1 --interface-name if-tunnel0-to-on-prem --ip-address 169.254.0.1 --mask-length 30 --vpn-tunnel vpc-demo-tunnel10 --region us-central1"
    - "gcloud compute routers add-bgp-peer vpc-demo-router1 --peer-name bgp-on-prem-tunnel0 --interface if-tunnel0-to-on-prem --peer-ip-address 169.254.0.2 --peer-asn 65002 --region us-central1"
    - "gcloud compute routers add-interface vpc-demo-router1 --interface-name if-tunnel1-to-on-prem --ip-address 169.254.1.1 --mask-length 30 --vpn-tunnel vpc-demo-tunnel1 --region us-central1"
    - "gcloud compute routers add-bgp-peer vpc-demo-router1 --peer-name bgp-on-prem-tunnel1 --interface if-tunnel1-to-on-prem --peer-ip-address 169.254.1.2 --peer-asn 65002 --region us-central1"
    - "gcloud compute routers add-interface on-prem-router1 --interface-name if-tunnel0-to-vpc-demo --ip-address 169.254.1.2 --peer-asn 65002 --region us-central1"
    - "gcloud compute routers add-bpg-peer on-prem-router1 --peer-name bgp-vpc-demo-tunnel0 --interface if-tunnel0-to-vpc-demo --peer-ip-address 169.254.0.1 --peer-asn 65001 --region us-central1"
    - "gcloud compute routers add-interface on-prem-router1 --interface-name if-tunnel1-to-vpc-demo --ip-address 169.254.1.2 --mask-length 30 --vpn-tunnel on-prem-tunnel1 --region us-central1"
    - "gcloud compute routers add-bgp-peer on-prem-router1 --peer-name bgp-vpc-demo-tunnel1 --interface if-tunnel1-to-vpc-demo --peer-ip-address 169.254.1.1 --peer-asn 65001 --region us-central1"

  - name: Verify Router Configurations
    tags: ['verify-router-configs']
    command: "{{ item }}"
    with_items:
    - "gcloud compute routers describe vpc-demo-router1 --region us-central1"
    - "gcloud compute routers describe on-prem-router1 --region us-central1"

  - name: Configure firewall rules to allow traffic from the remote VPC
    tags: ['configure-fw-allow-traffic-from-remote-vpc']
    command: "{{ item }}"
    with_items:
    - "gcloud compute firewall-rules create vpc-demo-allow-subnets-from-on-prem --network vpc-demo --allow tcp,udp,icmp --source-ranges 192.168.1.0/24"
    - "gcloud compute firewall-rules create on-prem-allow-subnets-from-vpc-demo --network on-prem -allow tcp,udp,icmp --source-ranges 10.1.1.0/24,10.2.1.0/24"

  - name: Verify status of tunnels
    tags: ['verify-status-of-tunnels']
    command: "{{ item }}"
    with_items:
    - "gcloud beta compute vpn-tunnels list"
    - "gcloud beta compute vpn-tunnels describe vpc-demo-tunnel0 --region us-central1"
    - "gcloud beta compute vpn-tunnels describe vpc-demo-tunnel1 --region us-central1"
    - "gcloud beta compute vpn-tunnels describe on-prem-tunnel0 --region us-central1"
    - "gcloud beta compute vpn-tunnels describe on-prem-tunnel1 --region us-central1"

  - name: Verify private connectivity over VPN
    tags: ['verify-private-connectivity-over-vpn']
    command: gcloud compute ssh on-prem-instance1 --zone us-central1-a -q --command "ping -c 4 10.1.1.2"

  - name: Global routing with VPN
    command: "{{ item }}"
    with_items:
    - "gcloud compute networks update vpc-demo --bgp-routing-mode GLOBAL"
    - "gcloud compute networks describe vpc-demo"
    - "gcloud compute ssh on-prem-instance1 --zone us-central1-a --command 'ping -c 4 10.2.1.2'"

  - name: Verify and test configuration of HA VPN tunnels
    command: "{{ item }}"
    with_items:
    - "gcloud compute vpn-tunnels delete vpc-demo-tunnel0 --region us-central1 --q"
    - "gcloud compute vpn-tunnels describe on-prem-tunnel0 --region us-central1"
    - "gcloud compute ssh on-prem-instance1 --zone us-central1-a --command 'ping -c 4 10.2.1.2'"
